[project]
name = "connect-4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipywidgets>=8.1.9",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pip>=26.2.1",
    "torch>=2.13.0",
    "tqdm>=4.70.0",
]

[project.scripts]
connect-4 = "connect_4:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
